//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoFenix.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfoFenix.Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS [document_directories] (
        ///    [id]    INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    [label] TEXT                NOT NULL,
        ///    [path]  TEXT                NOT NULL,
        ///    [code]  TEXT                NOT NULL,
        ///    [watch] INTEGER             NOT NULL,
        ///    [index] INTEGER             NOT NULL,
        ///
        ///    CONSTRAINT [UQ_document_directory_path] UNIQUE ([path])
        ///);
        ///
        ///CREATE TABLE IF NOT EXISTS [documents] (
        ///    [id]                    INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    [document_directo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateSchema {
            get {
                return ResourceManager.GetString("CreateSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    [id],
        ///    [document_directory_id],
        ///    [path],
        ///    [last_write_time],
        ///    [code],
        ///    [indexed],
        ///    [payload]
        ///FROM [documents]
        ///WHERE
        ///    (@ID IS NULL OR ([id] = @ID))
        ///AND (@Code IS NULL OR ([code] = @Code)).
        /// </summary>
        internal static string GetDocument {
            get {
                return ResourceManager.GetString("GetDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    [id],
        ///    [document_directory_id],
        ///    [path],
        ///    [last_write_time],
        ///    [code],
        ///    [indexed],
        ///    [payload]
        ///FROM [documents]
        ///WHERE
        ///    [path] = @Path.
        /// </summary>
        internal static string GetDocumentByPath {
            get {
                return ResourceManager.GetString("GetDocumentByPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    [document_directories].[id],
        ///    [document_directories].[label],
        ///    [document_directories].[path],
        ///    [document_directories].[code],
        ///    [document_directories].[watch],
        ///    [document_directories].[index],
        ///    (SELECT
        ///        COUNT([documents].[id])
        ///     FROM [documents]
        ///     WHERE
        ///        [documents].[document_directory_id] = [document_directories].[id]
        ///    ) AS [total_documents]
        ///FROM [document_directories]
        ///WHERE
        ///    [document_directories].[id] = @ID;.
        /// </summary>
        internal static string GetDocumentDirectory {
            get {
                return ResourceManager.GetString("GetDocumentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    [document_directories].[id],
        ///    [document_directories].[label],
        ///    [document_directories].[path],
        ///    [document_directories].[code],
        ///    [document_directories].[watch],
        ///    [document_directories].[index],
        ///    (SELECT
        ///        COUNT([documents].[id])
        ///     FROM [documents]
        ///     WHERE
        ///        [documents].[document_directory_id] = [document_directories].[id]
        ///    ) AS [total_documents]
        ///FROM [document_directories]
        ///WHERE
        ///    [document_directories].[path] = @Path;.
        /// </summary>
        internal static string GetDocumentDirectoryByPath {
            get {
                return ResourceManager.GetString("GetDocumentDirectoryByPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexar Documentos.
        /// </summary>
        internal static string IndexDocumentCollection_ProgressiveTask_Title {
            get {
                return ResourceManager.GetString("IndexDocumentCollection_ProgressiveTask_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    [document_directories].[id],
        ///    [document_directories].[label],
        ///    [document_directories].[path],
        ///    [document_directories].[code],
        ///    [document_directories].[watch],
        ///    [document_directories].[index],
        ///    (SELECT
        ///        COUNT([documents].[id])
        ///     FROM [documents]
        ///     WHERE
        ///        [documents].[document_directory_id] = [document_directories].[id]
        ///    ) AS [total_documents]
        ///FROM [document_directories]
        ///WHERE
        ///    (@Label IS NULL OR ([document_directories].[label] LIKE &apos;%&apos; + @ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListDocumentDirectories {
            get {
                return ResourceManager.GetString("ListDocumentDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    [documents].[id],
        ///    [documents].[document_directory_id],
        ///    [documents].[path],
        ///    [documents].[last_write_time],
        ///    [documents].[code],
        ///    [documents].[indexed],
        ///    [documents].[payload]
        ///FROM [documents]
        ///    INNER JOIN [document_directories] ON [document_directories].[id] = [documents].[document_directory_id]
        ///WHERE
        ///    [document_directories].[id] = @DocumentDirectoryID;.
        /// </summary>
        internal static string ListDocumentsByDocumentDirectory {
            get {
                return ResourceManager.GetString("ListDocumentsByDocumentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa cancelada!.
        /// </summary>
        internal static string ProgressiveTaskCancelNotification_Message {
            get {
                return ResourceManager.GetString("ProgressiveTaskCancelNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa concluída!.
        /// </summary>
        internal static string ProgressiveTaskCompleteNotification_Message {
            get {
                return ResourceManager.GetString("ProgressiveTaskCompleteNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro durante execução da tarefa!.
        /// </summary>
        internal static string ProgressiveTaskErrorNotification_Message {
            get {
                return ResourceManager.GetString("ProgressiveTaskErrorNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando tarefa....
        /// </summary>
        internal static string ProgressiveTaskStartNotification_Message {
            get {
                return ResourceManager.GetString("ProgressiveTaskStartNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [documents]
        ///WHERE
        ///    [id] = @ID;.
        /// </summary>
        internal static string RemoveDocument {
            get {
                return ResourceManager.GetString("RemoveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo documentos do índice.
        /// </summary>
        internal static string RemoveDocumentCollection_ProgressiveTaskPerformStep_Index_Message {
            get {
                return ResourceManager.GetString("RemoveDocumentCollection_ProgressiveTaskPerformStep_Index_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo documento: {0}.
        /// </summary>
        internal static string RemoveDocumentCollection_ProgressiveTaskPerformStep_Message {
            get {
                return ResourceManager.GetString("RemoveDocumentCollection_ProgressiveTaskPerformStep_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Documentos.
        /// </summary>
        internal static string RemoveDocumentCollection_ProgressiveTaskStart_Title {
            get {
                return ResourceManager.GetString("RemoveDocumentCollection_ProgressiveTaskStart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [documents]
        ///WHERE
        ///    [document_directory_id] = @DocumentDirectoryID;
        ///
        ///DELETE FROM [document_directories]
        ///WHERE
        ///    [id] = @DocumentDirectoryID;.
        /// </summary>
        internal static string RemoveDocumentDirectory {
            get {
                return ResourceManager.GetString("RemoveDocumentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Diretório de Documentos.
        /// </summary>
        internal static string RemoveDocumentDirectory_ProgressiveTask_Title {
            get {
                return ResourceManager.GetString("RemoveDocumentDirectory_ProgressiveTask_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT OR REPLACE INTO [documents] (
        ///    [id],
        ///    [document_directory_id],
        ///    [path],
        ///    [last_write_time],
        ///    [code],
        ///    [indexed],
        ///    [payload]
        ///) VALUES (
        ///    @ID,
        ///    @DocumentDirectoryID,
        ///    @Path,
        ///    @LastWriteTime,
        ///    @Code,
        ///    @Indexed,
        ///    @Payload
        ///);
        ///SELECT MAX([id]) FROM [documents];.
        /// </summary>
        internal static string SaveDocument {
            get {
                return ResourceManager.GetString("SaveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvando documento: {0}.
        /// </summary>
        internal static string SaveDocumentCollection_ProgressiveTaskPerformStep_Message {
            get {
                return ResourceManager.GetString("SaveDocumentCollection_ProgressiveTaskPerformStep_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar Documentos.
        /// </summary>
        internal static string SaveDocumentCollection_ProgressiveTaskStart_Title {
            get {
                return ResourceManager.GetString("SaveDocumentCollection_ProgressiveTaskStart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT OR REPLACE INTO [document_directories] (
        ///    [id],
        ///    [label],
        ///    [path],
        ///    [code],
        ///    [watch],
        ///    [index]
        ///) VALUES (
        ///    @ID,
        ///    @Label,
        ///    @Path,
        ///    @Code,
        ///    @Watch,
        ///    @Index
        ///);
        ///SELECT MAX([id]) FROM [document_directories].
        /// </summary>
        internal static string SaveDocumentDirectory {
            get {
                return ResourceManager.GetString("SaveDocumentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar Diretório de Documentos.
        /// </summary>
        internal static string SaveDocumentDirectory_ProgressiveTask_Title {
            get {
                return ResourceManager.GetString("SaveDocumentDirectory_ProgressiveTask_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [documents] SET
        ///    [indexed] = 1
        ///WHERE
        ///    [id] = @ID.
        /// </summary>
        internal static string SetDocumentIndex {
            get {
                return ResourceManager.GetString("SetDocumentIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observar Diretório de Documentos.
        /// </summary>
        internal static string StartWatchDocumentDirectory_ProgressiveTask_Title {
            get {
                return ResourceManager.GetString("StartWatchDocumentDirectory_ProgressiveTask_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberar Diretório de Documentos.
        /// </summary>
        internal static string StopWatchDocumentDirectory_ProgressiveTask_Title {
            get {
                return ResourceManager.GetString("StopWatchDocumentDirectory_ProgressiveTask_Title", resourceCulture);
            }
        }
    }
}
