//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoFenix.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfoFenix.Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicialização concluída! Por favor, aguarde....
        /// </summary>
        internal static string Bootstrapper_ProgressiveTaskComplete_Message {
            get {
                return ResourceManager.GetString("Bootstrapper_ProgressiveTaskComplete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa: {0}.
        /// </summary>
        internal static string Bootstrapper_ProgressiveTaskPerformStep_Message {
            get {
                return ResourceManager.GetString("Bootstrapper_ProgressiveTaskPerformStep_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializado Aplicativo.
        /// </summary>
        internal static string Bootstrapper_ProgressiveTaskStart_Title {
            get {
                return ResourceManager.GetString("Bootstrapper_ProgressiveTaskStart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar Diretório de Documentos.
        /// </summary>
        internal static string CleanDocumentDirectory_Progress_Start_Title {
            get {
                return ResourceManager.GetString("CleanDocumentDirectory_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo documento &quot;{0}&quot; da base de dados..
        /// </summary>
        internal static string CleanDocumentDirectory_Progress_Step_Database_Message {
            get {
                return ResourceManager.GetString("CleanDocumentDirectory_Progress_Step_Database_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo documentos do índice &quot;{0}&quot;..
        /// </summary>
        internal static string CleanDocumentDirectory_Progress_Step_Index_Message {
            get {
                return ResourceManager.GetString("CleanDocumentDirectory_Progress_Step_Index_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE IF NOT EXISTS [document_directories] (
        ///    [id]    INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    [label] TEXT                NOT NULL,
        ///    [path]  TEXT                NOT NULL,
        ///    [code]  TEXT                NOT NULL,
        ///    [watch] INTEGER             NOT NULL,
        ///    [index] INTEGER             NOT NULL,
        ///
        ///    CONSTRAINT [UQ_document_directory_path] UNIQUE ([path])
        ///);
        ///
        ///CREATE TABLE IF NOT EXISTS [documents] (
        ///    [id]                    INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    [document_directo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateSchemaSQL {
            get {
                return ResourceManager.GetString("CreateSchemaSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro fatal. O aplicativo será finalizado..
        /// </summary>
        internal static string FatalException_Message {
            get {
                return ResourceManager.GetString("FatalException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    [id],
        ///    [document_directory_id],
        ///    [path],
        ///    [last_write_time],
        ///    [code],
        ///    [indexed],
        ///    [payload]
        ///FROM [documents]
        ///WHERE
        ///    [path] = @path.
        /// </summary>
        internal static string GetDocumentByPathSQL {
            get {
                return ResourceManager.GetString("GetDocumentByPathSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    [document_directories].[id],
        ///    [document_directories].[label],
        ///    [document_directories].[path],
        ///    [document_directories].[code],
        ///    [document_directories].[watch],
        ///    [document_directories].[index],
        ///    (SELECT
        ///        COUNT([documents].[id])
        ///     FROM [documents]
        ///     WHERE
        ///        [documents].[document_directory_id] = [document_directories].[id]
        ///    ) AS [total_documents]
        ///FROM [document_directories]
        ///WHERE
        ///    [document_directories].[path] = @path;.
        /// </summary>
        internal static string GetDocumentDirectoryByPathSQL {
            get {
                return ResourceManager.GetString("GetDocumentDirectoryByPathSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    [document_directories].[id],
        ///    [document_directories].[label],
        ///    [document_directories].[path],
        ///    [document_directories].[code],
        ///    [document_directories].[watch],
        ///    [document_directories].[index],
        ///    (SELECT
        ///        COUNT([documents].[id])
        ///     FROM [documents]
        ///     WHERE
        ///        [documents].[document_directory_id] = [document_directories].[id]
        ///    ) AS [total_documents]
        ///FROM [document_directories]
        ///WHERE
        ///    [document_directories].[id] = @id;.
        /// </summary>
        internal static string GetDocumentDirectorySQL {
            get {
                return ResourceManager.GetString("GetDocumentDirectorySQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    [id],
        ///    [document_directory_id],
        ///    [path],
        ///    [last_write_time],
        ///    [code],
        ///    [indexed],
        ///    [payload]
        ///FROM [documents]
        ///WHERE
        ///    (@id IS NULL OR ([id] = @id))
        ///AND (@code IS NULL OR ([code] = @code)).
        /// </summary>
        internal static string GetDocumentSQL {
            get {
                return ResourceManager.GetString("GetDocumentSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexar Documento.
        /// </summary>
        internal static string IndexDocument_Progress_Start_Title {
            get {
                return ResourceManager.GetString("IndexDocument_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravando documento: {0}.
        /// </summary>
        internal static string IndexDocument_Progress_Step_Database_Message {
            get {
                return ResourceManager.GetString("IndexDocument_Progress_Step_Database_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexando documento: {0}.
        /// </summary>
        internal static string IndexDocument_Progress_Step_Index_Message {
            get {
                return ResourceManager.GetString("IndexDocument_Progress_Step_Index_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexar Documentos.
        /// </summary>
        internal static string IndexDocumentCollection_Progress_Start_Title {
            get {
                return ResourceManager.GetString("IndexDocumentCollection_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexando documento: {0}.
        /// </summary>
        internal static string IndexDocumentCollection_Progress_Step_Message {
            get {
                return ResourceManager.GetString("IndexDocumentCollection_Progress_Step_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    [document_directories].[id],
        ///    [document_directories].[label],
        ///    [document_directories].[path],
        ///    [document_directories].[code],
        ///    [document_directories].[watch],
        ///    [document_directories].[index],
        ///    (SELECT
        ///        COUNT([documents].[id])
        ///     FROM [documents]
        ///     WHERE
        ///        [documents].[document_directory_id] = [document_directories].[id]
        ///    ) AS [total_documents]
        ///FROM [document_directories]
        ///WHERE
        ///    (@label IS NULL OR ([document_directories].[label] LIKE &apos;%&apos; + @ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListDocumentDirectoriesSQL {
            get {
                return ResourceManager.GetString("ListDocumentDirectoriesSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///    [documents].[id],
        ///    [documents].[document_directory_id],
        ///    [documents].[path],
        ///    [documents].[last_write_time],
        ///    [documents].[code],
        ///    [documents].[indexed],
        ///    [documents].[payload]
        ///FROM [documents]
        ///    INNER JOIN [document_directories] ON [document_directories].[id] = [documents].[document_directory_id]
        ///WHERE
        ///    [document_directories].[id] = @document_directory_id;.
        /// </summary>
        internal static string ListDocumentsByDocumentDirectorySQL {
            get {
                return ResourceManager.GetString("ListDocumentsByDocumentDirectorySQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tarefa foi cancelada!.
        /// </summary>
        internal static string Progress_Cancel {
            get {
                return ResourceManager.GetString("Progress_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tarefa foi concluída com sucesso!.
        /// </summary>
        internal static string Progress_Complete {
            get {
                return ResourceManager.GetString("Progress_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro durante execução da tarefa!.
        /// </summary>
        internal static string Progress_Error {
            get {
                return ResourceManager.GetString("Progress_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executando passo {0} da tarefa....
        /// </summary>
        internal static string Progress_PerformStep {
            get {
                return ResourceManager.GetString("Progress_PerformStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa Iniciada.
        /// </summary>
        internal static string Progress_Start {
            get {
                return ResourceManager.GetString("Progress_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa cancelada!.
        /// </summary>
        internal static string ProgressiveTaskCancelNotification_Message {
            get {
                return ResourceManager.GetString("ProgressiveTaskCancelNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa concluída!.
        /// </summary>
        internal static string ProgressiveTaskCompleteNotification_Message {
            get {
                return ResourceManager.GetString("ProgressiveTaskCompleteNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro durante execução da tarefa!.
        /// </summary>
        internal static string ProgressiveTaskErrorNotification_Message {
            get {
                return ResourceManager.GetString("ProgressiveTaskErrorNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando tarefa....
        /// </summary>
        internal static string ProgressiveTaskStartNotification_Message {
            get {
                return ResourceManager.GetString("ProgressiveTaskStartNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Documento.
        /// </summary>
        internal static string RemoveDocument_Progress_Start_Title {
            get {
                return ResourceManager.GetString("RemoveDocument_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo documento da base de dados: {0}.
        /// </summary>
        internal static string RemoveDocument_Progress_Step_Database_Message {
            get {
                return ResourceManager.GetString("RemoveDocument_Progress_Step_Database_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo documento do índice: {0}.
        /// </summary>
        internal static string RemoveDocument_Progress_Step_Index_Message {
            get {
                return ResourceManager.GetString("RemoveDocument_Progress_Step_Index_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Documentos.
        /// </summary>
        internal static string RemoveDocumentCollection_Progress_Start_Title {
            get {
                return ResourceManager.GetString("RemoveDocumentCollection_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo documento da base de dados: {0}.
        /// </summary>
        internal static string RemoveDocumentCollection_Progress_Step_Database_Message {
            get {
                return ResourceManager.GetString("RemoveDocumentCollection_Progress_Step_Database_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo documentos do índice.
        /// </summary>
        internal static string RemoveDocumentCollection_Progress_Step_Index_Message {
            get {
                return ResourceManager.GetString("RemoveDocumentCollection_Progress_Step_Index_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Diretório de Documentos.
        /// </summary>
        internal static string RemoveDocumentDirectory_Progress_Start_Title {
            get {
                return ResourceManager.GetString("RemoveDocumentDirectory_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo diretório de documentos &quot;{0}&quot; da base de dados..
        /// </summary>
        internal static string RemoveDocumentDirectory_Progress_Step_Database_Message {
            get {
                return ResourceManager.GetString("RemoveDocumentDirectory_Progress_Step_Database_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo diretório de documentos &quot;{0}&quot; do índice..
        /// </summary>
        internal static string RemoveDocumentDirectory_Progress_Step_Index_Message {
            get {
                return ResourceManager.GetString("RemoveDocumentDirectory_Progress_Step_Index_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM [documents]
        ///WHERE
        ///    [document_directory_id] = @document_directory_id;
        ///
        ///DELETE FROM [document_directories]
        ///WHERE
        ///    [id] = @document_directory_id;.
        /// </summary>
        internal static string RemoveDocumentDirectorySQL {
            get {
                return ResourceManager.GetString("RemoveDocumentDirectorySQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE
        ///FROM [documents]
        ///WHERE
        ///    [id] = @id;.
        /// </summary>
        internal static string RemoveDocumentSQL {
            get {
                return ResourceManager.GetString("RemoveDocumentSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar Documento.
        /// </summary>
        internal static string SaveDocument_Progress_Start_Title {
            get {
                return ResourceManager.GetString("SaveDocument_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvando documento: {0}.
        /// </summary>
        internal static string SaveDocument_Progress_Step_Message {
            get {
                return ResourceManager.GetString("SaveDocument_Progress_Step_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar Documentos.
        /// </summary>
        internal static string SaveDocumentCollection_Progress_Start_Title {
            get {
                return ResourceManager.GetString("SaveDocumentCollection_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvando documento: {0}.
        /// </summary>
        internal static string SaveDocumentCollection_Progress_Step_Message {
            get {
                return ResourceManager.GetString("SaveDocumentCollection_Progress_Step_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar Documentos do Diretório de Documentos.
        /// </summary>
        internal static string SaveDocumentCollectionInDocumentDirectory_Progress_Start_Title {
            get {
                return ResourceManager.GetString("SaveDocumentCollectionInDocumentDirectory_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvando documento: {0}.
        /// </summary>
        internal static string SaveDocumentCollectionInDocumentDirectory_Progress_Step_Message {
            get {
                return ResourceManager.GetString("SaveDocumentCollectionInDocumentDirectory_Progress_Step_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar Diretório de Documentos.
        /// </summary>
        internal static string SaveDocumentDirectory_Progress_Start_Title {
            get {
                return ResourceManager.GetString("SaveDocumentDirectory_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvando diretório de documentos: {0}.
        /// </summary>
        internal static string SaveDocumentDirectory_Progress_Step_Message {
            get {
                return ResourceManager.GetString("SaveDocumentDirectory_Progress_Step_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT OR REPLACE INTO [document_directories] (
        ///    [id],
        ///    [label],
        ///    [path],
        ///    [code],
        ///    [watch],
        ///    [index]
        ///) VALUES (
        ///    @id,
        ///    @label,
        ///    @path,
        ///    @code,
        ///    @watch,
        ///    @index
        ///);
        ///SELECT MAX([id]) FROM [document_directories].
        /// </summary>
        internal static string SaveDocumentDirectorySQL {
            get {
                return ResourceManager.GetString("SaveDocumentDirectorySQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT OR REPLACE INTO [documents] (
        ///    [id],
        ///    [document_directory_id],
        ///    [path],
        ///    [last_write_time],
        ///    [code],
        ///    [indexed],
        ///    [payload]
        ///) VALUES (
        ///    @id,
        ///    @document_directory_id,
        ///    @path,
        ///    @last_write_time,
        ///    @code,
        ///    @indexed,
        ///    @payload
        ///);
        ///SELECT MAX([id]) FROM [documents];.
        /// </summary>
        internal static string SaveDocumentSQL {
            get {
                return ResourceManager.GetString("SaveDocumentSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar Índices.
        /// </summary>
        internal static string SearchDocumentIndex_Progress_Start_Title {
            get {
                return ResourceManager.GetString("SearchDocumentIndex_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construíndo pesquisa....
        /// </summary>
        internal static string SearchDocumentIndex_Progress_Step_Build_Message {
            get {
                return ResourceManager.GetString("SearchDocumentIndex_Progress_Step_Build_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisando índice: {0}.
        /// </summary>
        internal static string SearchDocumentIndex_Progress_Step_Search_Message {
            get {
                return ResourceManager.GetString("SearchDocumentIndex_Progress_Step_Search_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [documents] SET
        ///    [indexed] = 1
        ///WHERE
        ///    [id] = @id.
        /// </summary>
        internal static string SetDocumentIndexSQL {
            get {
                return ResourceManager.GetString("SetDocumentIndexSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observar Diretório de Documentos.
        /// </summary>
        internal static string StartWatchDocumentDirectory_Progress_Start_Title {
            get {
                return ResourceManager.GetString("StartWatchDocumentDirectory_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observando diretório de documentos: {0}.
        /// </summary>
        internal static string StartWatchDocumentDirectory_Progress_Step_Message {
            get {
                return ResourceManager.GetString("StartWatchDocumentDirectory_Progress_Step_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberar Diretório de Documentos.
        /// </summary>
        internal static string StopWatchDocumentDirectory_Progress_Start_Title {
            get {
                return ResourceManager.GetString("StopWatchDocumentDirectory_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liberando diretório de documentos: {0}.
        /// </summary>
        internal static string StopWatchDocumentDirectory_Progress_Step_Message {
            get {
                return ResourceManager.GetString("StopWatchDocumentDirectory_Progress_Step_Message", resourceCulture);
            }
        }
    }
}
