//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoFenix.Impl.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfoFenix.Impl.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CREATE TABLE IF NOT EXISTS [document_directories] (
        ///    [document_directory_id] INTEGER PRIMARY KEY AUTOINCREMENT,
        ///    [label]                 TEXT                NOT NULL,
        ///    [directory_path]        TEXT                NOT NULL,
        ///    [code]                  TEXT                NOT NULL,
        ///    [watch]                 INTEGER             NOT NULL,
        ///    [index]                 INTEGER             NOT NULL,
        ///
        ///    CONSTRAINT [UQ_directory_path] UNIQUE ([directory_path])
        ///);
        ///
        ///CREATE TABLE IF NOT EXISTS [do [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string CreateSchema {
            get {
                return ResourceManager.GetString("CreateSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT
        ///    [document_directory_id],
        ///    [label],
        ///    [directory_path],
        ///    [code],
        ///    [watch],
        ///    [index]
        ///FROM [document_directories]
        ///WHERE
        ///    (@Label IS NULL OR ([label] LIKE &apos;%&apos; + @Label + &apos;%&apos;))
        ///AND (@DirectoryPath IS NULL OR ([directory_path] LIKE &apos;%&apos; + @DirectoryPath + &apos;%&apos;))
        ///AND (@Code IS NULL OR ([code] LIKE &apos;%&apos; + @Code + &apos;%&apos;))
        ///AND (@Watch IS NULL OR ([watch] = @Watch))
        ///AND (@Index IS NULL OR ([index] = @Index));.
        /// </summary>
        internal static string ListDocumentDirectories {
            get {
                return ResourceManager.GetString("ListDocumentDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT
        ///    [documents].[document_id],
        ///    [documents].[document_directory_id],
        ///    [documents].[file_name],
        ///    [documents].[full_path],
        ///    [documents].[last_write_time],
        ///    [documents].[code],
        ///    [documents].[indexed],
        ///    [documents].[payload]
        ///FROM [documents]
        ///    INNER JOIN [document_directories] ON [document_directories].[document_directory_id] = [documents].[document_directory_id]
        ///WHERE
        ///    [document_directories].[document_directory_id] = @DocumentDirectoryID;.
        /// </summary>
        internal static string ListDocumentsByDocumentDirectory {
            get {
                return ResourceManager.GetString("ListDocumentsByDocumentDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT OR REPLACE INTO [document_directories] (
        ///    [document_directory_id],
        ///    [label],
        ///    [directory_path],
        ///    [code],
        ///    [watch],
        ///    [index]
        ///) VALUES (
        ///    @DocumentDirectoryID,
        ///    @Label,
        ///    @DirectoryPath,
        ///    @Code,
        ///    @Watch,
        ///    @Index
        ///);
        ///SELECT MAX([document_directory_id]) FROM [document_directories].
        /// </summary>
        internal static string SaveDocumentDirectory {
            get {
                return ResourceManager.GetString("SaveDocumentDirectory", resourceCulture);
            }
        }
    }
}
