//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoFenix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfoFenix.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicialização concluída! Por favor, aguarde....
        /// </summary>
        public static string Bootstrapper_ProgressiveTaskComplete_Message {
            get {
                return ResourceManager.GetString("Bootstrapper_ProgressiveTaskComplete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa: {0}.
        /// </summary>
        public static string Bootstrapper_ProgressiveTaskPerformStep_Message {
            get {
                return ResourceManager.GetString("Bootstrapper_ProgressiveTaskPerformStep_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicializado Aplicativo.
        /// </summary>
        public static string Bootstrapper_ProgressiveTaskStart_Title {
            get {
                return ResourceManager.GetString("Bootstrapper_ProgressiveTaskStart_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar Diretório de Documentos.
        /// </summary>
        public static string CleanDocumentDirectory_Progress_Start_Title {
            get {
                return ResourceManager.GetString("CleanDocumentDirectory_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo documento &quot;{0}&quot; da base de dados..
        /// </summary>
        public static string CleanDocumentDirectory_Progress_Step_Database_Message {
            get {
                return ResourceManager.GetString("CleanDocumentDirectory_Progress_Step_Database_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo documentos do índice &quot;{0}&quot;..
        /// </summary>
        public static string CleanDocumentDirectory_Progress_Step_Index_Message {
            get {
                return ResourceManager.GetString("CleanDocumentDirectory_Progress_Step_Index_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar diretório de destino.
        /// </summary>
        public static string ConfigurationForm_SelectDatabaseBackupDirectory {
            get {
                return ResourceManager.GetString("ConfigurationForm_SelectDatabaseBackupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar arquivo de restauração.
        /// </summary>
        public static string ConfigurationForm_SelectDatabaseRestoreFile {
            get {
                return ResourceManager.GetString("ConfigurationForm_SelectDatabaseRestoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar a Base de Dados.
        /// </summary>
        public static string DatabaseCleanUp_Progress_Start_Title {
            get {
                return ResourceManager.GetString("DatabaseCleanUp_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, aguarde. Limpando a base de dados....
        /// </summary>
        public static string DatabaseCleanUp_Progress_Step_Database_Message {
            get {
                return ResourceManager.GetString("DatabaseCleanUp_Progress_Step_Database_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ver.{0}.{1}.{2}.
        /// </summary>
        public static string Display_Version {
            get {
                return ResourceManager.GetString("Display_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar o caminho do diretório de documentos.
        /// </summary>
        public static string DocumentDirectoryForm_SelectDocumentDirectoryPath_Message {
            get {
                return ResourceManager.GetString("DocumentDirectoryForm_SelectDocumentDirectoryPath_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro fatal. O aplicativo será finalizado..
        /// </summary>
        public static string FatalException_Message {
            get {
                return ResourceManager.GetString("FatalException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexar Documentos.
        /// </summary>
        public static string IndexDocumentDirectory_Progress_Start_Title {
            get {
                return ResourceManager.GetString("IndexDocumentDirectory_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexando documento: {0}.
        /// </summary>
        public static string IndexDocumentDirectory_Progress_Step_Message {
            get {
                return ResourceManager.GetString("IndexDocumentDirectory_Progress_Step_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexado.
        /// </summary>
        public static string Indexed {
            get {
                return ResourceManager.GetString("Indexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente sair do aplicativo?.
        /// </summary>
        public static string MainForm_Exit_Message {
            get {
                return ResourceManager.GetString("MainForm_Exit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário reiniciar o aplicativo..
        /// </summary>
        public static string MustRebootApplication {
            get {
                return ResourceManager.GetString("MustRebootApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não indexado.
        /// </summary>
        public static string NonIndexed {
            get {
                return ResourceManager.GetString("NonIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tarefa foi cancelada!.
        /// </summary>
        public static string Progress_Cancel {
            get {
                return ResourceManager.GetString("Progress_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tarefa foi concluída com sucesso!.
        /// </summary>
        public static string Progress_Complete {
            get {
                return ResourceManager.GetString("Progress_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro durante execução da tarefa!.
        /// </summary>
        public static string Progress_Error {
            get {
                return ResourceManager.GetString("Progress_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executando passo {0} da tarefa....
        /// </summary>
        public static string Progress_PerformStep {
            get {
                return ResourceManager.GetString("Progress_PerformStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa Iniciada.
        /// </summary>
        public static string Progress_Start {
            get {
                return ResourceManager.GetString("Progress_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa cancelada!.
        /// </summary>
        public static string ProgressiveTaskCancelNotification_Message {
            get {
                return ResourceManager.GetString("ProgressiveTaskCancelNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarefa concluída!.
        /// </summary>
        public static string ProgressiveTaskCompleteNotification_Message {
            get {
                return ResourceManager.GetString("ProgressiveTaskCompleteNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro durante execução da tarefa!.
        /// </summary>
        public static string ProgressiveTaskErrorNotification_Message {
            get {
                return ResourceManager.GetString("ProgressiveTaskErrorNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando tarefa....
        /// </summary>
        public static string ProgressiveTaskStartNotification_Message {
            get {
                return ResourceManager.GetString("ProgressiveTaskStartNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancelar.
        /// </summary>
        public static string ProgressViewForm_ActionButton_Cancel {
            get {
                return ResourceManager.GetString("ProgressViewForm_ActionButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Fechar.
        /// </summary>
        public static string ProgressViewForm_ActionButton_Close {
            get {
                return ResourceManager.GetString("ProgressViewForm_ActionButton_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente cancelar a tarefa?.
        /// </summary>
        public static string ProgressViewForm_Cancellation_Message {
            get {
                return ResourceManager.GetString("ProgressViewForm_Cancellation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar Tarefa.
        /// </summary>
        public static string ProgressViewForm_Cancellation_Title {
            get {
                return ResourceManager.GetString("ProgressViewForm_Cancellation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reiniciar.
        /// </summary>
        public static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover Diretório de Documentos.
        /// </summary>
        public static string RemoveDocumentDirectory_Progress_Start_Title {
            get {
                return ResourceManager.GetString("RemoveDocumentDirectory_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo diretório de documentos &quot;{0}&quot; da base de dados..
        /// </summary>
        public static string RemoveDocumentDirectory_Progress_Step_Database_Message {
            get {
                return ResourceManager.GetString("RemoveDocumentDirectory_Progress_Step_Database_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removendo diretório de documentos &quot;{0}&quot; do índice..
        /// </summary>
        public static string RemoveDocumentDirectory_Progress_Step_Index_Message {
            get {
                return ResourceManager.GetString("RemoveDocumentDirectory_Progress_Step_Index_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar Diretório de Documentos.
        /// </summary>
        public static string SaveDocumentDirectory_Progress_Start_Title {
            get {
                return ResourceManager.GetString("SaveDocumentDirectory_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvando diretório de documentos: {0}.
        /// </summary>
        public static string SaveDocumentDirectory_Progress_Step_Message {
            get {
                return ResourceManager.GetString("SaveDocumentDirectory_Progress_Step_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar Documentos do Diretório de Documentos.
        /// </summary>
        public static string SaveDocumentDirectoryDocuments_Progress_Start_Title {
            get {
                return ResourceManager.GetString("SaveDocumentDirectoryDocuments_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvando documento: {0}.
        /// </summary>
        public static string SaveDocumentDirectoryDocuments_Progress_Step_Message {
            get {
                return ResourceManager.GetString("SaveDocumentDirectoryDocuments_Progress_Step_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar Índices.
        /// </summary>
        public static string SearchDocumentIndex_Progress_Start_Title {
            get {
                return ResourceManager.GetString("SearchDocumentIndex_Progress_Start_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construíndo pesquisa....
        /// </summary>
        public static string SearchDocumentIndex_Progress_Step_Build_Message {
            get {
                return ResourceManager.GetString("SearchDocumentIndex_Progress_Step_Build_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisando índice: {0}.
        /// </summary>
        public static string SearchDocumentIndex_Progress_Step_Search_Message {
            get {
                return ResourceManager.GetString("SearchDocumentIndex_Progress_Step_Search_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível retornar resultados para o(s) termo(s) pesquisado(s)..
        /// </summary>
        public static string SearchForm_EmptyResultSet {
            get {
                return ResourceManager.GetString("SearchForm_EmptyResultSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do documento: {0}.
        /// </summary>
        public static string SearchResultForm_DocumentPathLabel {
            get {
                return ResourceManager.GetString("SearchResultForm_DocumentPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento {0} de {1}.
        /// </summary>
        public static string SearchResultForm_InformationLabel {
            get {
                return ResourceManager.GetString("SearchResultForm_InformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} de {1}.
        /// </summary>
        public static string SplashScreenForm_ActualStep_TotalSteps {
            get {
                return ResourceManager.GetString("SplashScreenForm_ActualStep_TotalSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto selecionado foi copiado para a área de transferência.
        /// </summary>
        public static string TextCopiedToClipboard {
            get {
                return ResourceManager.GetString("TextCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de documentos: {0}.
        /// </summary>
        public static string TotalDocumentsMessage {
            get {
                return ResourceManager.GetString("TotalDocumentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro: {0}.
        /// </summary>
        public static string WaitForForm_Error_Message {
            get {
                return ResourceManager.GetString("WaitForForm_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação concluída com sucesso!.
        /// </summary>
        public static string WaitForForm_Success_Message {
            get {
                return ResourceManager.GetString("WaitForForm_Success_Message", resourceCulture);
            }
        }
    }
}
