//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoFenix.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfoFenix.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_folder_32x32 {
            get {
                object obj = ResourceManager.GetObject("add_folder_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É obrigatório selecionar a pasta da base de dados remota, se utilizar o modo remoto..
        /// </summary>
        internal static string ConfigurationForm_MustSelectApplicationDataDirectory {
            get {
                return ResourceManager.GetString("ConfigurationForm_MustSelectApplicationDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar diretório de dados do aplicativo.
        /// </summary>
        internal static string ConfigurationForm_SelectApplicationDataDirectory {
            get {
                return ResourceManager.GetString("ConfigurationForm_SelectApplicationDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar diretório de destino.
        /// </summary>
        internal static string ConfigurationForm_SelectDatabaseBackupDirectory {
            get {
                return ResourceManager.GetString("ConfigurationForm_SelectDatabaseBackupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar arquivo de restauração.
        /// </summary>
        internal static string ConfigurationForm_SelectDatabaseRestoreFile {
            get {
                return ResourceManager.GetString("ConfigurationForm_SelectDatabaseRestoreFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copiar.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_128x128 {
            get {
                object obj = ResourceManager.GetObject("copy_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_64x64 {
            get {
                object obj = ResourceManager.GetObject("copy_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap copy_text_16x16 {
            get {
                object obj = ResourceManager.GetObject("copy-text_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_backup_32x32 {
            get {
                object obj = ResourceManager.GetObject("database-backup_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap database_restore_32x32 {
            get {
                object obj = ResourceManager.GetObject("database-restore_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ver.{0}.{1}.{2}.
        /// </summary>
        internal static string Display_Version {
            get {
                return ResourceManager.GetString("Display_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap document_directory_128x128 {
            get {
                object obj = ResourceManager.GetObject("document_directory_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar o caminho do diretório de documentos.
        /// </summary>
        internal static string DocumentDirectoryForm_SelectDocumentDirectoryPath_Message {
            get {
                return ResourceManager.GetString("DocumentDirectoryForm_SelectDocumentDirectoryPath_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit_128x128 {
            get {
                object obj = ResourceManager.GetObject("exit_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit_64x64 {
            get {
                object obj = ResourceManager.GetObject("exit_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fast_forward_128x128 {
            get {
                object obj = ResourceManager.GetObject("fast_forward_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fast_forward_64x64 {
            get {
                object obj = ResourceManager.GetObject("fast_forward_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fast_rewind_128x128 {
            get {
                object obj = ResourceManager.GetObject("fast_rewind_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fast_rewind_64x64 {
            get {
                object obj = ResourceManager.GetObject("fast_rewind_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_32x32 {
            get {
                object obj = ResourceManager.GetObject("folder_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forward_128x128 {
            get {
                object obj = ResourceManager.GetObject("forward_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap forward_64x64 {
            get {
                object obj = ResourceManager.GetObject("forward_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap goto_128x128 {
            get {
                object obj = ResourceManager.GetObject("goto_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap goto_64x64 {
            get {
                object obj = ResourceManager.GetObject("goto_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap help_128x128 {
            get {
                object obj = ResourceManager.GetObject("help_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hourglass_20x20 {
            get {
                object obj = ResourceManager.GetObject("hourglass_20x20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hourglass_32x32 {
            get {
                object obj = ResourceManager.GetObject("hourglass_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap index_128x128 {
            get {
                object obj = ResourceManager.GetObject("index_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexado.
        /// </summary>
        internal static string Indexed {
            get {
                return ResourceManager.GetString("Indexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon info_fenix_113x128 {
            get {
                object obj = ResourceManager.GetObject("info_fenix_113x128", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap info_fenix_84x95 {
            get {
                object obj = ResourceManager.GetObject("info_fenix_84x95", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente sair do aplicativo?.
        /// </summary>
        internal static string MainForm_Exit_Message {
            get {
                return ResourceManager.GetString("MainForm_Exit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário reiniciar o aplicativo..
        /// </summary>
        internal static string MustRebootApplication {
            get {
                return ResourceManager.GetString("MustRebootApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não indexado.
        /// </summary>
        internal static string NonIndexed {
            get {
                return ResourceManager.GetString("NonIndexed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancelar.
        /// </summary>
        internal static string ProgressViewForm_ActionButton_Cancel {
            get {
                return ResourceManager.GetString("ProgressViewForm_ActionButton_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Fechar.
        /// </summary>
        internal static string ProgressViewForm_ActionButton_Close {
            get {
                return ResourceManager.GetString("ProgressViewForm_ActionButton_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja realmente cancelar a tarefa?.
        /// </summary>
        internal static string ProgressViewForm_Cancellation_Message {
            get {
                return ResourceManager.GetString("ProgressViewForm_Cancellation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar Tarefa.
        /// </summary>
        internal static string ProgressViewForm_Cancellation_Title {
            get {
                return ResourceManager.GetString("ProgressViewForm_Cancellation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reiniciar.
        /// </summary>
        internal static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rewind_128x128 {
            get {
                object obj = ResourceManager.GetObject("rewind_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rewind_64x64 {
            get {
                object obj = ResourceManager.GetObject("rewind_64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_128x128 {
            get {
                object obj = ResourceManager.GetObject("search_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_result_128x128 {
            get {
                object obj = ResourceManager.GetObject("search_result_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível retornar resultados para o(s) termo(s) pesquisado(s)..
        /// </summary>
        internal static string SearchForm_EmptyResultSet {
            get {
                return ResourceManager.GetString("SearchForm_EmptyResultSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do documento: {0}.
        /// </summary>
        internal static string SearchResultForm_DocumentPathLabel {
            get {
                return ResourceManager.GetString("SearchResultForm_DocumentPathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento {0} de {1}.
        /// </summary>
        internal static string SearchResultForm_InformationLabel {
            get {
                return ResourceManager.GetString("SearchResultForm_InformationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settings_128x128 {
            get {
                object obj = ResourceManager.GetObject("settings_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} de {1}.
        /// </summary>
        internal static string SplashScreenForm_ActualStep_TotalSteps {
            get {
                return ResourceManager.GetString("SplashScreenForm_ActualStep_TotalSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap starting_128x128 {
            get {
                object obj = ResourceManager.GetObject("starting_128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucesso.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texto selecionado foi copiado para a área de transferência.
        /// </summary>
        internal static string TextCopiedToClipboard {
            get {
                return ResourceManager.GetString("TextCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total de documentos: {0}.
        /// </summary>
        internal static string TotalDocumentsMessage {
            get {
                return ResourceManager.GetString("TotalDocumentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro: {0}.
        /// </summary>
        internal static string WaitForForm_Error_Message {
            get {
                return ResourceManager.GetString("WaitForForm_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação concluída com sucesso!.
        /// </summary>
        internal static string WaitForForm_Success_Message {
            get {
                return ResourceManager.GetString("WaitForForm_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap word_document_doc_blue_32x32 {
            get {
                object obj = ResourceManager.GetObject("word_document_doc_blue_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap word_document_doc_gray_32x32 {
            get {
                object obj = ResourceManager.GetObject("word_document_doc_gray_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap word_document_docx_blue_32x32 {
            get {
                object obj = ResourceManager.GetObject("word_document_docx_blue_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap word_document_docx_gray_32x32 {
            get {
                object obj = ResourceManager.GetObject("word_document_docx_gray_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
